### ISSUE TITLE
No module named pysnptools.snpreader.bed

### ISSUE THREAD

**Issue by rtahmasbi** [omerwe/PCGCs#1]
Hi,
I got the following error after running `pcgcs_direct.py --bfile1 $geno_ped --pheno1 $phen_cc --covar1 $phen_cov --prev1 $prev`:

```Traceback (most recent call last):
  File "/scratch/summit/PRJ041_AscertainmentCaseControl/20180304_sim_cov/PCGCs/pcgcs_direct.py", line 14, in <module>
    import pcgcs_utils
  File "/gpfs/summit/scratch/PRJ041_AscertainmentCaseControl/20180304_sim_cov/PCGCs/pcgcs_utils.py", line 9, in <module>
    from pysnptools.snpreader.bed import Bed
ImportError: No module named pysnptools.snpreader.bed
```
Best,
Rasool

**Comment by omerwe** [comment]
Hi Rasool,

It sounds like you have a problem with the installation of the  pysnptools
package
Please try to reinstall/update it via the command: "pip install --user
--upgrade pysnptools".

Best,

Omer

**Comment by rtahmasbi** [comment]
Solved!
Thanks
